apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookbag.name" . }}
  labels:
    {{- include "bookbag.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "bookbag.selectorLabels" . | nindent 4 }}
